server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 아이디
    password: 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://아이피:3306/greendb 
      driver-class-name: org.mariadb.jdbc.Driver
      username: 유저명
      password: 비밀번호

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

file:
  path: /home/ubuntu/upload/